feat: implement basic CRUD of the Application model
ass-g8/acme-explorer pull request #3
Opened 2023-02-06 09:24 UTC by mrf1989

2023-02-06 17:23 UTC, alemunara approved these changes
¿Vamos a crear un fichero en el directorio de servicio por cada uri distinta que necesitemos?

2023-02-07 09:18 UTC, marmolpen3 commented
@alemunara aparentemente es necesario al usar oas-tool

2023-02-07 09:22 UTC, marmolpen3 requested changes
Creo que debe existir un problema con el creado de la aplicación desde swagger, ya que los atributos de las entidades no se llaman igual

2023-02-07 09:51 UTC, mrf1989 commented
Vale, reviso la forma en la que se están llamando a los atributos y corrijo.

2023-02-07 10:24 UTC, mrf1989 commented
He probado todas las operaciones CRUD de Application al completo y funciona.

2023-02-07 14:54 UTC, marmolpen3 approved these changes

2023-02-07 14:54 UTC, merged